import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Section } from "@/components/layout/section";
import { SectionHeading } from "@/components/layout/section-heading";
import { Logo } from "@/components/ui/logo";
import { ThemeToggle } from "@/components/theme/theme-toggle";

const badgeVariants = ["neutral", "primary", "success", "warning", "danger", "information"] as const;

export default function DesignSystemPage() {
  return <main><Section spacing="compact"><div className="flex items-start justify-between gap-5"><SectionHeading eyebrow="DEVELOPMENT PREVIEW" title="Workey UI foundation" description="A focused visual check for shared layout, primitives, typography, themes, and RTL readiness." action={<Logo />} /><ThemeToggle /></div></Section>
    <Section surface="muted"><SectionHeading eyebrow="ACTIONS" title="Buttons and badges" /><div className="mt-6 flex flex-wrap gap-3"><Button>Primary action</Button><Button variant="secondary">Secondary</Button><Button variant="outline">Outline</Button><Button variant="ghost">Ghost</Button><Button variant="danger">Danger</Button><Button disabled>Disabled</Button><Button loading>Loading</Button></div><div className="mt-5 flex flex-wrap gap-3">{badgeVariants.map((variant) => <Badge key={variant} variant={variant}>{variant}</Badge>)}</div></Section>
    <Section><SectionHeading eyebrow="FORMS" title="Input states" /><div className="mt-6 grid gap-5 md:grid-cols-2"><Input description="This helper text is associated with the field." label="Email address" placeholder="you@example.com" required type="email" /><Input error="Enter a valid location." label="Location" placeholder="City or remote" type="text" /><Input disabled label="Disabled field" placeholder="Unavailable" type="text" /><Input label="Search" leading={<span>⌕</span>} placeholder="Search roles" trailing={<Button size="small" type="button" variant="ghost">Clear</Button>} type="search" /></div></Section>
    <Section surface="muted"><SectionHeading eyebrow="SURFACES" title="Cards and spacing" description="Default surfaces rely on borders and hierarchy; elevation and glass remain selective." /><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><p className="type-heading-3 text-text-primary">Default</p><p className="type-body-small mt-2 text-text-secondary">Clean, bordered surface.</p></Card><Card variant="muted"><p className="type-heading-3 text-text-primary">Muted</p><p className="type-body-small mt-2 text-text-secondary">Supporting context.</p></Card><Card variant="elevated"><p className="type-heading-3 text-text-primary">Elevated</p><p className="type-body-small mt-2 text-text-secondary">Restrained card shadow.</p></Card><Card variant="interactive" tabIndex={0}><p className="type-heading-3 text-text-primary">Interactive</p><p className="type-body-small mt-2 text-text-secondary">Focus and hover check.</p></Card></div><div className="mt-4"><Card variant="glass"><p className="type-heading-3 text-text-primary">Optional glass surface</p><p className="type-body-small mt-2 text-text-secondary">Solid fallback remains readable when blur is unavailable.</p></Card></div></Section>
    <Section spacing="spacious"><SectionHeading eyebrow="LAYOUT" title="Consistent content rhythm" description="Every section uses the shared centered container and one of three token-backed vertical spacing options." /><div className="mt-6 grid gap-4 md:grid-cols-3"><Card><p className="type-heading-3 text-text-primary">Compact</p><p className="type-body-small mt-2 text-text-secondary">For concise supporting areas.</p></Card><Card variant="elevated"><p className="type-heading-3 text-text-primary">Standard</p><p className="type-body-small mt-2 text-text-secondary">The default page rhythm.</p></Card><Card><p className="type-heading-3 text-text-primary">Spacious</p><p className="type-body-small mt-2 text-text-secondary">For larger visual breaks.</p></Card></div></Section>
    <Section><SectionHeading align="center" eyebrow="TYPE SCALE" title="Clear, reusable hierarchy" description="Page headings, section headings, cards, body text, labels, and captions share the central token scale." /><div className="mt-6 grid gap-3"><p className="type-display text-text-primary">Display heading</p><p className="type-heading-1 text-text-primary">Page heading</p><p className="type-heading-2 text-text-primary">Section heading</p><p className="type-heading-3 text-text-primary">Card heading</p><p className="type-body text-text-secondary">Body copy is sized for comfortable, readable job-seeker interfaces.</p><p className="type-body-small text-text-muted">Small supporting copy and labels remain easy to scan.</p></div></Section>
    <Section surface="surface"><div dir="rtl" lang="ar"><SectionHeading eyebrow="معاينة عربية" title="اكتشف فرصتك المهنية القادمة" description="ابحث عن الوظائف التي تناسب مهاراتك وخبراتك، وتابع طلباتك في مكان واحد." /></div></Section>
  </main>;
}
