"use client";

import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { SectionSkeleton } from "@/components/feedback/section-skeleton";
import { SectionState } from "@/components/feedback/section-state";
import { JobCard } from "@/components/jobs/job-card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ApiError } from "@/lib/api/errors";
import { getPublicJobs } from "@/lib/api/jobs";
import { routes } from "@/config/routes";
import type { Job, JobsQuery, PaginationMeta } from "@/lib/api/types";

const PAGE_SIZE = 12;
type SortDirection = "asc" | "desc";
interface JobsSearchState { search: string; location: string; workMode: string; sortDirection: SortDirection; page: number; }

function numberValue(value: string | null) { const parsed = Number(value); return Number.isInteger(parsed) && parsed > 0 ? parsed : 1; }
function stateFromParams(params: URLSearchParams): JobsSearchState { return { search: params.get("search") ?? "", location: params.get("location") ?? "", workMode: ["remote", "hybrid", "on_site"].includes(params.get("work_mode") ?? "") ? params.get("work_mode") ?? "" : "", sortDirection: params.get("sort_direction") === "asc" ? "asc" : "desc", page: numberValue(params.get("page")) }; }
function urlFor(state: JobsSearchState) { const params = new URLSearchParams(); if (state.search.trim()) params.set("search", state.search.trim()); if (state.location.trim()) params.set("location", state.location.trim()); if (state.workMode) params.set("work_mode", state.workMode); if (state.sortDirection === "asc") { params.set("sort_by", "published_at"); params.set("sort_direction", "asc"); } if (state.page > 1) params.set("page", String(state.page)); return `${routes.explore}${params.size ? `?${params.toString()}` : ""}`; }
function queryFor(state: JobsSearchState): JobsQuery { return { search: state.search.trim() || undefined, location: state.location.trim() || undefined, work_mode: state.workMode || undefined, sort_by: "published_at", sort_direction: state.sortDirection, accepting_applications: true, page: state.page, per_page: PAGE_SIZE }; }
function hasFilters(state: JobsSearchState) { return Boolean(state.search.trim() || state.location.trim() || state.workMode || state.sortDirection === "asc"); }
function paginationPages(current: number, last: number) { const pages = new Set([1, last, current - 1, current, current + 1]); return [...pages].filter((page) => page >= 1 && page <= last).sort((left, right) => left - right); }

function JobsSearchControls({ initialState, loading, summary, onReset, onSearch, onSort }: { initialState: JobsSearchState; loading: boolean; summary: string; onReset: () => void; onSearch: (state: JobsSearchState) => void; onSort: (direction: SortDirection) => void; }) {
  const [draft, setDraft] = useState(initialState);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); onSearch({ ...draft, page: 1 }); }
  function updateSort(sortDirection: SortDirection) { const next = { ...draft, sortDirection, page: 1 }; setDraft(next); onSort(sortDirection); }
  return <><form className="radius-large mt-7 grid gap-3 border border-border-default bg-surface p-5 md:grid-cols-[1fr_1fr_minmax(9rem,.7fr)_auto] md:items-end" onSubmit={submit} role="search"><Input label="Job title or keyword" name="search" onChange={(event) => setDraft((current) => ({ ...current, search: event.target.value }))} placeholder="e.g. product designer" type="search" value={draft.search} /><Input label="Location" name="location" onChange={(event) => setDraft((current) => ({ ...current, location: event.target.value }))} placeholder="City or remote" value={draft.location} /><label className="grid gap-2 type-body-small text-text-secondary"><span className="font-medium text-text-primary">Work style</span><select className="ui-select" name="work_mode" onChange={(event) => setDraft((current) => ({ ...current, workMode: event.target.value }))} value={draft.workMode}><option value="">Any style</option><option value="remote">Remote</option><option value="hybrid">Hybrid</option><option value="on_site">On-site</option></select></label><Button loading={loading} type="submit">Search jobs</Button></form><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="type-body-small text-text-secondary">{summary}</p>{hasFilters(initialState) ? <Button className="mt-3" onClick={onReset} size="small" type="button" variant="ghost">Reset all filters</Button> : null}</div><label className="grid gap-2 type-body-small text-text-secondary"><span className="font-medium text-text-primary">Sort by</span><select className="ui-select min-w-40" onChange={(event) => updateSort(event.target.value as SortDirection)} value={draft.sortDirection}><option value="desc">Newest</option><option value="asc">Oldest</option></select></label></div></>;
}

export function JobsExplorer() {
  const router = useRouter(); const searchParams = useSearchParams(); const resultsRef = useRef<HTMLDivElement | null>(null); const controller = useRef<AbortController | null>(null); const requestId = useRef(0);
  const queryString = searchParams.toString(); const activeState = useMemo(() => stateFromParams(new URLSearchParams(queryString)), [queryString]);
  const [jobs, setJobs] = useState<Job[]>([]); const [meta, setMeta] = useState<PaginationMeta | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const loadJobs = useCallback(async (state: JobsSearchState) => { controller.current?.abort(); const activeController = new AbortController(); controller.current = activeController; const id = ++requestId.current; setLoading(true); setError(null); try { const response = await getPublicJobs(queryFor(state), activeController.signal); if (id !== requestId.current) return; setJobs(response.data); setMeta(response.meta); } catch (reason) { if (activeController.signal.aborted || id !== requestId.current) return; setError(reason instanceof ApiError && reason.code === "service_unavailable" ? "Job search is temporarily unavailable. Please try again shortly." : "We could not update the opportunities right now."); } finally { if (id === requestId.current) setLoading(false); } }, []);
  useEffect(() => { // URL changes are an external synchronization source; the request itself owns the pending state.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void loadJobs(activeState); return () => controller.current?.abort(); }, [activeState, loadJobs]);
  function navigate(next: JobsSearchState, shouldScroll = false) { router.push(urlFor(next), { scroll: false }); if (shouldScroll) { const behavior = window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth"; resultsRef.current?.scrollIntoView({ behavior, block: "start" }); } }
  function reset() { const empty: JobsSearchState = { search: "", location: "", workMode: "", sortDirection: "desc", page: 1 }; navigate(empty); }
  const firstResult = meta && meta.total ? (meta.current_page - 1) * meta.per_page + 1 : 0; const lastResult = meta ? Math.min(meta.current_page * meta.per_page, meta.total) : 0; const pages = meta ? paginationPages(meta.current_page, meta.last_page) : [];
  return <><JobsSearchControls initialState={activeState} key={queryString} loading={loading} onReset={reset} onSearch={(state) => navigate(state)} onSort={(sortDirection) => navigate({ ...activeState, sortDirection, page: 1 })} summary={meta ? meta.total ? `Showing ${firstResult}–${lastResult} of ${meta.total} public opportunities` : "No public opportunities found" : "Loading current opportunities"} /><div aria-busy={loading} aria-live="polite" className="mt-8 min-h-80" id="jobs-results" ref={resultsRef}><p className="sr-only">{loading ? "Loading job results" : error ? "Job search could not be updated" : meta ? `${meta.total} job results available` : ""}</p>{loading ? <SectionSkeleton cards={PAGE_SIZE} className="md:grid-cols-2 xl:grid-cols-3" /> : error ? <div className="ui-card ui-card--muted"><p className="type-body text-text-primary">{error}</p><Button className="mt-4" onClick={() => void loadJobs(activeState)} type="button" variant="outline">Try again</Button></div> : jobs.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{jobs.map((job) => <JobCard job={job} key={job.id} />)}</div> : <SectionState title="No matching opportunities" description={hasFilters(activeState) ? "Try broadening your keyword, location, or work-style search." : "There are no public opportunities to show right now."} />}</div>{meta && meta.last_page > 1 ? <nav aria-label="Job results pages" className="mt-8"><div className="hidden items-center justify-center gap-2 sm:flex"><Button disabled={loading || meta.current_page <= 1} onClick={() => navigate({ ...activeState, page: activeState.page - 1 }, true)} size="small" type="button" variant="outline">Previous</Button>{pages.map((page, index) => <span className="flex items-center gap-2" key={page}>{index > 0 && page - pages[index - 1] > 1 ? <span aria-hidden="true">…</span> : null}<Button aria-current={page === meta.current_page ? "page" : undefined} disabled={loading} onClick={() => navigate({ ...activeState, page }, true)} size="small" type="button" variant={page === meta.current_page ? "primary" : "outline"}>{page}</Button></span>)}<Button disabled={loading || meta.current_page >= meta.last_page} onClick={() => navigate({ ...activeState, page: activeState.page + 1 }, true)} size="small" type="button" variant="outline">Next</Button></div><div className="flex items-center justify-between gap-3 sm:hidden"><Button disabled={loading || meta.current_page <= 1} onClick={() => navigate({ ...activeState, page: activeState.page - 1 }, true)} size="small" type="button" variant="outline">Previous</Button><p className="type-body-small text-text-secondary">Page {meta.current_page} of {meta.last_page}</p><Button disabled={loading || meta.current_page >= meta.last_page} onClick={() => navigate({ ...activeState, page: activeState.page + 1 }, true)} size="small" type="button" variant="outline">Next</Button></div></nav> : null}</>;
}
