import type { JobSeekerProfileDetail } from "@/lib/auth/types";

export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export interface CVLabel { key: string; label?: string; value?: string; }
export interface CVProgress { upload_completed: boolean; text_extracted: boolean; parsing_completed: boolean; review_completed: boolean; }
export interface CVNextAction { type?: CVLabel; key?: string; value?: string; target?: { type?: string; id?: number } | string; is_actionable?: boolean; }
export interface CurrentCV { id: number; original_name: string; mime_type: string; extension: string; size_bytes: number; stage?: CVLabel; confirmed_at: string | null; can_use_for_application: boolean; allowed_actions: string[]; created_at: string | null; updated_at: string | null; }
export interface PendingCVUpdate { id: number; original_name: string; mime_type: string; extension: string; size_bytes: number; operation?: CVLabel; stage?: CVLabel; progress?: CVProgress; next_action?: CVNextAction | null; can_use_for_application: boolean; allowed_actions: string[]; created_at: string | null; updated_at: string | null; error?: { message?: string; code?: string } | null; }
export type CVWorkflowStatus = "no_cv" | "processing" | "review_required" | "suggestions_review_required" | "ready_for_confirmation" | "confirmed" | "failed" | string;
export interface ProfileCVState { status: CVLabel; is_ready: boolean; pending_update?: PendingCVUpdate | null; allowed_actions: string[]; preview_url?: string | null; download_url?: string | null; }
export interface CVReviewDraftProfile { headline?: string | null; phone: string | null; summary: string | null; location: string | null; city_id?: number | null; portfolio_url?: string | null; linkedin_url?: string | null; github_url?: string | null; }
export interface CVReviewExperience { id?: number; title: string; company_name: string; location: string | null; start_date: string | null; end_date: string | null; is_current: boolean; description: string | null; }
export interface CVReviewEducation { id?: number; institution: string; degree: string | null; field_of_study: string | null; start_date: string | null; end_date: string | null; description: string | null; }
export interface CVReviewDraft { profile: CVReviewDraftProfile; experience: CVReviewExperience[]; education: CVReviewEducation[]; skills: string[]; [key: string]: JsonValue | CVReviewDraftProfile | CVReviewExperience[] | CVReviewEducation[] | string[]; }
export interface CVReviewValidationSummary { is_valid: boolean; errors: Array<string | { field?: string; message?: string }>; }
export interface CVComparisonSummary { total: number; add: number; update: number; merge: number; ignore: number; resolved: number; unresolved: number; }
export type CVChangeSummary = Record<string, JsonValue>;
export interface CVParsingResult { id?: number; parsed_json?: JsonValue; reviewed_json?: JsonValue; status?: CVLabel; errors?: JsonValue; created_at?: string | null; updated_at?: string | null; }
export interface CVReview { cv_file_id: number; operation?: CVLabel; stage?: CVLabel; parsing_status: CVLabel; review_mode: CVLabel; review_status: CVLabel; next_action: CVLabel | null; can_edit_draft: boolean; can_generate_suggestions: boolean; can_apply_suggestions: boolean; can_confirm?: boolean; editable_sections: string[]; read_only_sections: string[]; draft?: CVReviewDraft | null; parsed_json?: JsonValue; reviewed_json?: JsonValue; final_profile?: JsonValue; validation_summary?: CVReviewValidationSummary; comparison_summary?: CVComparisonSummary; change_summary?: CVChangeSummary; allowed_actions?: string[]; reviewed_at: string | null; }
export interface CVSuggestion { id: number; cv_file_id: number; entity_type: CVLabel; suggestion_type: CVLabel; status: CVLabel; source: CVLabel; old_value: JsonValue; new_value: JsonValue; user_edited_value: JsonValue; current_value?: JsonValue; proposed_value?: JsonValue; editable_value?: JsonValue; default_decision?: string | null; selected_decision?: string | null; allowed_decisions?: string[]; can_accept: boolean; can_reject: boolean; can_edit: boolean; can_apply: boolean; is_actionable: boolean; display_group: CVLabel; applied_at: string | null; decided_at: string | null; created_at: string | null; updated_at: string | null; }
export interface CVUploadResult extends CurrentCV { version_label: string | null; parsing_status: CVLabel; status: CVLabel; review_mode: CVLabel; review_status: CVLabel; next_action: CVLabel; is_primary: boolean; is_archived: boolean; is_cancelled?: boolean; can_set_primary: boolean; can_archive: boolean; can_restore: boolean; can_cancel?: boolean; parsing_result?: CVParsingResult | null; parsed_at: string | null; }
export interface CVConfirmResult { profile: JobSeekerProfileDetail; suggestions: CVSuggestion[]; current_cv?: CurrentCV | null; pending_cv_update?: PendingCVUpdate | null; applied_changes?: JsonValue; already_confirmed?: boolean; }
export interface CVCancelResult { current_cv: CurrentCV | null; pending_cv_update: PendingCVUpdate | null; already_cancelled: boolean; }
export type CVSuggestionsResult = CVSuggestion[] | { data: CVSuggestion[]; comparison_summary?: CVComparisonSummary };
