"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { AccountApiError, cancelCV, refreshProfile, uploadCV } from "@/lib/account/cv-client";
import type { CVWorkflowStatus } from "@/lib/account/cv-types";
import type { JobSeekerProfileDetail } from "@/lib/auth/types";
import { CVWorkflowModal } from "./cv-workflow-modal";

type ModalMode = "review" | "suggestions" | "confirm";
const maxSize = 5 * 1024 * 1024;
function formatBytes(bytes: number) { if (bytes < 1024) return `${bytes} B`; const units = ["KB", "MB", "GB"]; let value = bytes / 1024; let unit = units[0]; for (let index = 1; value >= 1024 && index < units.length; index += 1) { value /= 1024; unit = units[index]; } return `${new Intl.NumberFormat("en", { maximumFractionDigits: value < 10 ? 1 : 0 }).format(value)} ${unit}`; }
function formatDate(value: string | null) { return value && !Number.isNaN(Date.parse(value)) ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value)) : null; }
function supportsUpload(file: File) { return file.size <= maxSize && (file.type === "application/pdf" || file.type === "application/vnd.openxmlformats-officedocument.wordprocessingml.document" || /\.(pdf|docx)$/i.test(file.name)); }
function label(value?: { label?: string; value?: string; key?: string } | null) { return value?.label ?? value?.value ?? value?.key?.replaceAll("_", " ") ?? null; }

export function CVControlCenter({ profile, onProfileChange, onNotice }: { profile: JobSeekerProfileDetail; onProfileChange: (profile: JobSeekerProfileDetail) => void; onNotice: (message: string) => void }) {
  const inputRef = useRef<HTMLInputElement>(null); const polling = useRef(false); const mounted = useRef(true); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<AccountApiError | null>(null); const [modal, setModal] = useState<ModalMode | null>(null); const state = (profile.cv?.status?.key ?? (profile.current_cv ? "confirmed" : "no_cv")) as CVWorkflowStatus; const pending = profile.pending_cv_update;
  const refresh = useCallback(async () => { const next = await refreshProfile(); if (mounted.current) onProfileChange(next); return next; }, [onProfileChange]);
  useEffect(() => () => { mounted.current = false; }, []);
  useEffect(() => { if (state !== "processing") return; const poll = async () => { if (document.visibilityState !== "visible" || polling.current) return; polling.current = true; try { await refresh(); } catch { /* Keep the stable profile visible during transient polling errors. */ } finally { polling.current = false; } }; const timer = window.setInterval(() => void poll(), 5000); return () => window.clearInterval(timer); }, [refresh, state]);
  async function choose(file: File) { if (!supportsUpload(file)) { setError(new AccountApiError(422, "Choose a PDF or DOCX file up to 5 MB.")); return; } setBusy("upload"); setError(null); try { await uploadCV(file); await refresh(); onNotice("CV uploaded. Workey is preparing it for review."); } catch (reason) { setError(reason instanceof AccountApiError ? reason : new AccountApiError(500, "CV could not be uploaded.")); } finally { setBusy(null); } }
  async function cancelPending() { if (!pending || !window.confirm("Discard this pending CV workflow? Your current confirmed CV will stay unchanged.")) return; setBusy("cancel"); setError(null); try { const result = await cancelCV(pending.id); await refresh(); onNotice(result.already_cancelled ? "The pending CV was already discarded." : "Pending CV discarded. Your current CV was not changed."); setModal(null); } catch (reason) { setError(reason instanceof AccountApiError ? reason : new AccountApiError(500, "The pending CV could not be discarded.")); } finally { setBusy(null); } }
  const canUpload = state === "no_cv" || state === "confirmed" || profile.cv?.allowed_actions?.some((action) => action === "upload_cv" || action === "update_cv");
  const modalMode: ModalMode | null = state === "review_required" ? "review" : state === "suggestions_review_required" ? "suggestions" : state === "ready_for_confirmation" ? "confirm" : null;
  const stateCopy: Record<string, [string, string]> = { processing: ["Your CV is being analyzed", "We are extracting structured information. This page will update when the backend finishes."], review_required: ["Your CV has been analyzed", "Review the information extracted from your CV before saving anything into your profile."], suggestions_review_required: ["We found changes in your new CV", "Compare the uploaded CV with your current profile and decide what should change."], ready_for_confirmation: ["Your reviewed CV is ready to confirm", "Review the final structured information and explicitly confirm it as your current CV."], failed: ["This CV could not be processed", "Your current confirmed profile and CV were not changed."], confirmed: ["Your current CV is ready", "This confirmed CV is generated from your structured profile and can be used for applications."], no_cv: ["Build your current CV", "Upload your PDF or DOCX and Workey will extract your professional information for review before anything changes."] };
  const [title, description] = stateCopy[state] ?? [label(profile.cv?.status) ?? "CV workflow", pending?.next_action?.type ? label(pending.next_action.type) ?? "Continue the backend-guided workflow." : "Continue the backend-guided workflow."];

  return <section className={`cv-control-center cv-control-center--${state}`} id="profile-cv"><header className="cv-control-center__header"><div><p>CV CONTROL CENTER</p><h2>{title}</h2><span>{description}</span></div><span className="cv-status-badge">{label(profile.cv?.status) ?? state.replaceAll("_", " ")}</span></header>{error ? <div className="cv-control-error" role="alert"><strong>{error.message}</strong>{error.code ? <span>Code: {error.code}</span> : null}{error.errors ? <ul>{Object.values(error.errors).flat().map((message) => <li key={message}>{message}</li>)}</ul> : null}</div> : null}
    {state === "no_cv" ? <UploadWorkspace busy={busy === "upload"} inputRef={inputRef} onChoose={choose} /> : <div className="cv-control-center__workspace">{profile.current_cv ? <CurrentCVCard profile={profile} /> : null}{pending ? <PendingCVCard busy={busy} onCancel={() => void cancelPending()} onContinue={modalMode ? () => setModal(modalMode) : undefined} pending={pending} state={state} /> : null}{state === "confirmed" && canUpload ? <div className="cv-update-panel"><div><strong>Keep your CV current</strong><p>Upload a new PDF or DOCX. Your confirmed CV remains usable throughout review.</p></div><Button disabled={busy !== null} onClick={() => inputRef.current?.click()} type="button" variant="outline">Update CV</Button></div> : null}{!pending && state !== "confirmed" && state !== "no_cv" ? <div className="cv-control-empty"><p>The backend did not return a pending CV for this workflow state.</p></div> : null}</div>}
    <input accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void choose(file); event.currentTarget.value = ""; }} ref={inputRef} type="file" />{modal && pending ? <CVWorkflowModal mode={modal} onClose={() => setModal(null)} onComplete={async () => { await refresh(); }} onNotice={onNotice} pending={pending} /> : null}</section>;
}

function UploadWorkspace({ busy, inputRef, onChoose }: { busy: boolean; inputRef: React.RefObject<HTMLInputElement | null>; onChoose: (file: File) => Promise<void> }) { const [dragging, setDragging] = useState(false); return <div className="cv-upload-workspace"><div className="cv-upload-copy"><div className="cv-feature-tags"><span>PDF / DOCX</span><span>Maximum 5 MB</span><span>One current CV</span></div><p>Your uploaded file is workflow input. Your confirmed CV is built from reviewed, structured profile information.</p></div><div className={`cv-dropzone${dragging ? " cv-dropzone--active" : ""}`} onDragEnter={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); setDragging(false); const file = event.dataTransfer.files[0]; if (file) void onChoose(file); }}><span aria-hidden="true">↑</span><strong>Drop your CV here</strong><p>PDF or DOCX, up to 5 MB</p><Button loading={busy} onClick={() => inputRef.current?.click()} type="button">Choose file</Button></div></div>; }
function CurrentCVCard({ profile }: { profile: JobSeekerProfileDetail }) { const cv = profile.current_cv!; const confirmed = formatDate(cv.confirmed_at); return <article className="cv-current-card"><header><div><span>CURRENT CV</span><h3>{cv.original_name}</h3></div><span className="cv-ready-mark">✓ Ready</span></header><div className="cv-file-meta"><span>{cv.extension.toUpperCase()}</span><span>{formatBytes(cv.size_bytes)}</span>{label(cv.stage) ? <span>{label(cv.stage)}</span> : null}{confirmed ? <time dateTime={cv.confirmed_at ?? undefined}>Confirmed {confirmed}</time> : null}</div><p>{cv.can_use_for_application ? "Ready for applications" : "Not currently available for applications"}</p><div className="cv-card-actions">{(cv.allowed_actions.includes("preview_cv") || profile.cv?.preview_url) ? <a className="ui-button ui-button--outline ui-button--small" href="/api/account/profile/cv/preview" rel="noreferrer" target="_blank">Preview</a> : null}{(cv.allowed_actions.includes("download_cv") || profile.cv?.download_url) ? <Link className="ui-button ui-button--ghost ui-button--small" href="/api/account/profile/cv/download">Download</Link> : null}</div></article>; }
function PendingCVCard({ busy, onCancel, onContinue, pending, state }: { busy: string | null; onCancel: () => void; onContinue?: () => void; pending: NonNullable<JobSeekerProfileDetail["pending_cv_update"]>; state: CVWorkflowStatus }) { const copy: Record<string, string> = { review_required: "Review extracted information", suggestions_review_required: "Review suggested changes", ready_for_confirmation: "Review & confirm" }; const progress = pending.progress; return <article className={`cv-pending-card cv-pending-card--${state}`}><header><div><span>{state === "failed" ? "FAILED UPLOAD" : "PENDING CV UPDATE"}</span><h3>{pending.original_name}</h3></div><span>{label(pending.stage) ?? state.replaceAll("_", " ")}</span></header><div className="cv-file-meta"><span>{pending.extension.toUpperCase()}</span><span>{formatBytes(pending.size_bytes)}</span>{label(pending.operation) ? <span>{label(pending.operation)}</span> : null}</div>{label(pending.next_action?.type) ? <p>Next: {label(pending.next_action?.type)}</p> : null}{state === "processing" && progress ? <div className="cv-progress-list" aria-label="CV processing progress">{[["Upload complete", progress.upload_completed], ["Text extracted", progress.text_extracted], ["Parsing complete", progress.parsing_completed], ["Review prepared", progress.review_completed]].map(([name, complete]) => <div data-complete={complete} key={String(name)}><span>{complete ? "✓" : "○"}</span><strong>{name}</strong></div>)}</div> : null}{state === "failed" ? <div className="cv-failed-note"><p>{pending.error?.message ?? "The backend could not process this file."}</p>{pending.error?.code ? <small>Code: {pending.error.code}</small> : null}</div> : null}<div className="cv-card-actions">{onContinue ? <Button onClick={onContinue} type="button">{copy[state] ?? label(pending.next_action?.type) ?? "Continue workflow"}</Button> : null}{pending.allowed_actions.includes("preview_cv") || ["review_required", "suggestions_review_required", "ready_for_confirmation"].includes(state) ? <a className="ui-button ui-button--outline" href={`/api/account/profile/cv/files/${pending.id}/preview`} rel="noreferrer" target="_blank">Preview uploaded file</a> : null}{pending.allowed_actions.includes("download_cv") ? <a className="ui-button ui-button--ghost" href={`/api/account/profile/cv/files/${pending.id}/download`}>Download</a> : null}{state !== "processing" || pending.allowed_actions.includes("cancel_cv") ? <Button loading={busy === "cancel"} onClick={onCancel} type="button" variant={state === "failed" ? "danger" : "ghost"}>{state === "failed" ? "Discard failed upload" : "Cancel update"}</Button> : null}</div></article>; }
