"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import type { CVReviewDraft, CVReviewEducation, CVReviewExperience } from "@/lib/account/cv-types";

type Tab = "profile" | "experience" | "education" | "skills";
const blankExperience = (): CVReviewExperience => ({ title: "", company_name: "", location: null, start_date: null, end_date: null, is_current: false, description: null });
const blankEducation = (): CVReviewEducation => ({ institution: "", degree: null, field_of_study: null, start_date: null, end_date: null, description: null });
const nullable = (value: string) => value.trim() || null;

export function CVReviewDraftEditor({ draft, editableSections, errors, onChange }: { draft: CVReviewDraft; editableSections: string[]; errors?: Record<string, string[]>; onChange: (draft: CVReviewDraft) => void }) {
  const tabs = (["profile", "experience", "education", "skills"] as Tab[]).filter((tab) => editableSections.includes(tab));
  const [tab, setTab] = useState<Tab>(tabs[0] ?? "profile");
  const updateProfile = (key: "phone" | "summary" | "location", value: string) => onChange({ ...draft, profile: { ...draft.profile, [key]: nullable(value) } });
  const updateExperience = (index: number, patch: Partial<CVReviewExperience>) => onChange({ ...draft, experience: draft.experience.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) });
  const updateEducation = (index: number, patch: Partial<CVReviewEducation>) => onChange({ ...draft, education: draft.education.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) });
  const fieldError = (path: string) => errors?.[path]?.[0];

  return <div className="cv-draft-editor"><nav aria-label="Review sections" className="cv-tabs">{tabs.map((item) => <button aria-current={tab === item ? "page" : undefined} key={item} onClick={() => setTab(item)} type="button">{item === "experience" ? "Experience" : item[0].toUpperCase() + item.slice(1)}</button>)}</nav>
    {tab === "profile" ? <div className="cv-draft-grid"><Input error={fieldError("profile.phone")} label="Phone" onChange={(event) => updateProfile("phone", event.target.value)} value={draft.profile.phone ?? ""} /><Input error={fieldError("profile.location")} label="Location" onChange={(event) => updateProfile("location", event.target.value)} value={draft.profile.location ?? ""} /><Textarea className="cv-draft-wide" error={fieldError("profile.summary")} label="Professional summary" onChange={(event) => updateProfile("summary", event.target.value)} rows={7} value={draft.profile.summary ?? ""} /></div> : null}
    {tab === "experience" ? <div className="cv-draft-cards">{draft.experience.map((item, index) => <article key={item.id ?? index}><header><h3>Experience {index + 1}</h3><Button onClick={() => onChange({ ...draft, experience: draft.experience.filter((_, itemIndex) => itemIndex !== index) })} size="small" type="button" variant="ghost">Remove</Button></header><div className="cv-draft-grid"><Input error={fieldError(`experience.${index}.title`)} label="Job title" onChange={(event) => updateExperience(index, { title: event.target.value })} required value={item.title} /><Input error={fieldError(`experience.${index}.company_name`)} label="Company" onChange={(event) => updateExperience(index, { company_name: event.target.value })} required value={item.company_name} /><Input label="Location" onChange={(event) => updateExperience(index, { location: nullable(event.target.value) })} value={item.location ?? ""} /><label className="cv-check"><input checked={item.is_current} onChange={(event) => updateExperience(index, { is_current: event.target.checked, ...(event.target.checked ? { end_date: null } : {}) })} type="checkbox" />Currently working here</label><Input label="Start date" onChange={(event) => updateExperience(index, { start_date: nullable(event.target.value) })} type="date" value={item.start_date ?? ""} /><Input disabled={item.is_current} error={fieldError(`experience.${index}.end_date`)} label="End date" onChange={(event) => updateExperience(index, { end_date: nullable(event.target.value) })} type="date" value={item.end_date ?? ""} /><Textarea className="cv-draft-wide" label="Description" onChange={(event) => updateExperience(index, { description: nullable(event.target.value) })} rows={4} value={item.description ?? ""} /></div></article>)}<Button onClick={() => onChange({ ...draft, experience: [...draft.experience, blankExperience()] })} type="button" variant="outline">Add experience</Button></div> : null}
    {tab === "education" ? <div className="cv-draft-cards">{draft.education.map((item, index) => <article key={item.id ?? index}><header><h3>Education {index + 1}</h3><Button onClick={() => onChange({ ...draft, education: draft.education.filter((_, itemIndex) => itemIndex !== index) })} size="small" type="button" variant="ghost">Remove</Button></header><div className="cv-draft-grid"><Input error={fieldError(`education.${index}.institution`)} label="Institution" onChange={(event) => updateEducation(index, { institution: event.target.value })} required value={item.institution} /><Input label="Degree" onChange={(event) => updateEducation(index, { degree: nullable(event.target.value) })} value={item.degree ?? ""} /><Input label="Field of study" onChange={(event) => updateEducation(index, { field_of_study: nullable(event.target.value) })} value={item.field_of_study ?? ""} /><Input label="Start date" onChange={(event) => updateEducation(index, { start_date: nullable(event.target.value) })} type="date" value={item.start_date ?? ""} /><Input error={fieldError(`education.${index}.end_date`)} label="End date" onChange={(event) => updateEducation(index, { end_date: nullable(event.target.value) })} type="date" value={item.end_date ?? ""} /><Textarea className="cv-draft-wide" label="Description" onChange={(event) => updateEducation(index, { description: nullable(event.target.value) })} rows={4} value={item.description ?? ""} /></div></article>)}<Button onClick={() => onChange({ ...draft, education: [...draft.education, blankEducation()] })} type="button" variant="outline">Add education</Button></div> : null}
    {tab === "skills" ? <SkillsEditor draft={draft} onChange={onChange} /> : null}
  </div>;
}

function SkillsEditor({ draft, onChange }: { draft: CVReviewDraft; onChange: (draft: CVReviewDraft) => void }) { const [skill, setSkill] = useState(""); function add() { const value = skill.trim(); if (!value || draft.skills.some((item) => item.toLocaleLowerCase() === value.toLocaleLowerCase())) return; onChange({ ...draft, skills: [...draft.skills, value] }); setSkill(""); } return <div className="cv-skills-editor"><div className="cv-skill-add"><Input label="Add a skill" onChange={(event) => setSkill(event.target.value)} value={skill} /><Button onClick={add} type="button" variant="outline">Add</Button></div><div className="profile-skills">{draft.skills.map((item) => <span key={item.toLocaleLowerCase()}>{item}<button aria-label={`Remove ${item}`} onClick={() => onChange({ ...draft, skills: draft.skills.filter((skillName) => skillName !== item) })} type="button">×</button></span>)}</div></div>; }
