"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { CompanyIdentity } from "@/components/jobs/company-identity";
import { Button } from "@/components/ui/button";
import type { ApplicationsList, ApplicationsMeta, JobApplicationDetails, JobApplicationSummary } from "@/lib/applications/types";

const pageSize = 30;
function record(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === "object" && !Array.isArray(value); }
function summary(value: unknown): value is JobApplicationSummary { return record(value) && typeof value.id === "number"; }
function date(value: string | null | undefined) { return value && !Number.isNaN(Date.parse(value)) ? new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)) : null; }
function parseList(value: unknown): ApplicationsList { const root = record(value) && "data" in value ? value.data : value; const data = record(root) && Array.isArray(root.data) ? root.data.filter(summary) : Array.isArray(root) ? root.filter(summary) : []; const metaValue = record(root) && record(root.meta) ? root.meta : null; const meta = metaValue && ["current_page", "last_page", "per_page", "total"].every((key) => typeof metaValue[key] === "number") ? metaValue as unknown as ApplicationsMeta : null; return { data, meta }; }
function message(error: unknown) { return error instanceof Error ? error.message : "Applications are temporarily unavailable."; }

export function ApplicationsWorkspace() {
  const router = useRouter(); const params = useSearchParams(); const listAbort = useRef<AbortController | null>(null); const detailAbort = useRef<AbortController | null>(null);
  const [list, setList] = useState<ApplicationsList>({ data: [], meta: null }); const [loading, setLoading] = useState(true); const [listError, setListError] = useState<string | null>(null); const [details, setDetails] = useState<JobApplicationDetails | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [detailError, setDetailError] = useState<string | null>(null);
  const selectedId = Number(params.get("selected")); const selected = Number.isInteger(selectedId) && selectedId > 0 ? selectedId : null; const page = Math.max(1, Number(params.get("page")) || 1);
  const update = useCallback((changes: Record<string, string | null>) => { const next = new URLSearchParams(params.toString()); Object.entries(changes).forEach(([key, value]) => value ? next.set(key, value) : next.delete(key)); router.push(`/applications${next.size ? `?${next.toString()}` : ""}`, { scroll: false }); }, [params, router]);
  const load = useCallback(async () => { listAbort.current?.abort(); const controller = new AbortController(); listAbort.current = controller; setLoading(true); setListError(null); try { const response = await fetch(`/api/applications?per_page=${pageSize}&page=${page}`, { cache: "no-store", signal: controller.signal }); const payload: unknown = await response.json(); if (!response.ok) throw new Error(record(payload) && typeof payload.message === "string" ? payload.message : "Applications are temporarily unavailable."); if (!controller.signal.aborted) setList(parseList(payload)); } catch (error) { if (!controller.signal.aborted) setListError(message(error)); } finally { if (!controller.signal.aborted) setLoading(false); } }, [page]);
  useEffect(() => { // URL-driven network loading owns this pending state.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load(); return () => listAbort.current?.abort(); }, [load]);
  useEffect(() => { if (loading || !list.data.length) return; if (!selected || !list.data.some((item) => item.id === selected)) update({ selected: String(list.data[0].id) }); }, [list.data, loading, selected, update]);
  useEffect(() => { // Detail loading is intentionally independent of the list.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    if (!selected) { setDetails(null); return; } detailAbort.current?.abort(); const controller = new AbortController(); detailAbort.current = controller; setDetailLoading(true); setDetailError(null); void (async () => { try { const response = await fetch(`/api/applications/${selected}`, { cache: "no-store", signal: controller.signal }); const payload: unknown = await response.json(); if (!response.ok) throw new Error(record(payload) && typeof payload.message === "string" ? payload.message : "Application details are temporarily unavailable."); if (record(payload) && summary(payload.data)) setDetails(payload.data as JobApplicationDetails); else throw new Error("Application details returned an unexpected response."); } catch (error) { if (!controller.signal.aborted) setDetailError(message(error)); } finally { if (!controller.signal.aborted) setDetailLoading(false); } })(); return () => controller.abort(); }, [selected]);
  const selectedSummary = useMemo(() => list.data.find((item) => item.id === selected) ?? null, [list.data, selected]);
  const total = list.meta?.total ?? list.data.length;
  return <div className="applications-page" dir="ltr" lang="en"><header className="applications-page__intro"><div><p className="applications-page__eyebrow">APPLICATIONS</p><h1 className="type-heading-1">My Applications</h1><p className="type-body text-text-secondary">Track your applications and the next steps that need your attention.</p></div><div className="applications-page__total"><strong>{total}</strong><span>Applications</span></div></header><p className="applications-page__contract-note" role="status">Search, status groups, and workflow actions become available when they are exposed by the applications API.</p><div className="applications-page__workspace"><section aria-busy={loading} className="applications-page__list"><div className="applications-page__list-heading"><h2 className="type-heading-3">All applications</h2><Button onClick={() => void load()} size="small" type="button" variant="outline">Refresh</Button></div>{listError ? <div className="applications-page__state"><p>{listError}</p><Button onClick={() => void load()} size="small" type="button">Retry</Button></div> : loading ? <div className="applications-page__state">Loading applications…</div> : list.data.length ? <div className="applications-page__cards">{list.data.map((application) => <ApplicationCard active={application.id === selected} application={application} key={application.id} onSelect={() => update({ selected: String(application.id) })} />)}</div> : <div className="applications-page__state">You have not submitted any applications yet.</div>}{list.meta && list.meta.last_page > 1 ? <nav aria-label="Application pages" className="applications-page__pagination"><Button disabled={page <= 1} onClick={() => update({ page: String(page - 1), selected: null })} size="small" type="button" variant="outline">Previous</Button><span>Page {list.meta.current_page} of {list.meta.last_page}</span><Button disabled={page >= list.meta.last_page} onClick={() => update({ page: String(page + 1), selected: null })} size="small" type="button" variant="outline">Next</Button></nav> : null}</section><aside className="applications-page__details">{detailLoading ? <div className="applications-page__state">Loading application details…</div> : detailError ? <div className="applications-page__state">{detailError}</div> : details ? <ApplicationDetails application={details} /> : selectedSummary ? <div className="applications-page__state">Select this application again to load its details.</div> : <div className="applications-page__state">Select an application to view its timeline and next steps.</div>}</aside></div></div>;
}

function ApplicationCard({ active, application, onSelect }: { active: boolean; application: JobApplicationSummary; onSelect: () => void }) { const job = application.job_posting; const company = job?.company; return <button aria-pressed={active} className={`application-card${active ? " application-card--active" : ""}`} onClick={onSelect} type="button"><CompanyIdentity logoUrl={company?.logo_url} name={company?.name ?? "Company"} size="small" /><span className="application-card__copy"><strong>{job?.title ?? "Application"}</strong><span>{company?.name ?? "Company"}{job?.location ? ` · ${job.location}` : ""}</span><small>Applied {date(application.created_at) ?? "recently"}</small></span><span className="application-card__status">{application.status?.value ?? "Application submitted"}</span></button>; }
function ApplicationDetails({ application }: { application: JobApplicationDetails }) { const job = application.job_posting; const company = job?.company; const history = Array.isArray(application.status_history) ? application.status_history : []; return <div className="application-details"><header><CompanyIdentity logoUrl={company?.logo_url} name={company?.name ?? "Company"} size="large" /><div><p>{company?.name ?? "Company"}</p><h2 className="type-heading-2">{job?.title ?? "Application"}</h2><span className="application-card__status">{application.status?.value ?? "Application submitted"}</span></div></header>{application.latest_information_request ? <section><h3>Information request</h3><p>{application.latest_information_request.can_respond ? "The employer has requested information from you." : "The latest information request is no longer open."}</p>{date(application.latest_information_request.due_at) ? <small>Due {date(application.latest_information_request.due_at)}</small> : null}</section> : null}{application.selected_cv ? <section><h3>Submitted CV</h3><a href={application.selected_cv.download_url} rel="noreferrer" target="_blank">Download {application.selected_cv.original_name}</a></section> : null}<section><h3>Application timeline</h3>{history.length ? <ol className="application-details__timeline">{history.map((event, index) => <li key={event.id ?? `${event.created_at ?? "event"}-${index}`}><strong>{event.status?.value ?? "Status updated"}</strong>{date(event.created_at) ? <span>{date(event.created_at)}</span> : null}</li>)}</ol> : <p>No status updates are available yet.</p>}</section></div>; }
