import { NextRequest, NextResponse } from "next/server";
import { AuthBackendError, authBackendRequest, isJobSeeker } from "@/lib/auth/backend";
import { clearPendingVerification, getPendingVerification, sessionCookieName, sessionCookieOptions } from "@/lib/auth/server";
import type { LoginData } from "@/lib/auth/types";
import { otpLength } from "@/lib/auth/verification";

export const dynamic = "force-dynamic";
const noStore = { "Cache-Control": "no-store, private" };
function errorResponse(error: unknown) { const authError = error instanceof AuthBackendError ? error : new AuthBackendError(503, "Verification is temporarily unavailable."); const messages: Record<string, string> = { INVALID_OTP: "The verification code is incorrect.", OTP_EXPIRED: "This verification code has expired. Request a new code.", EMAIL_VERIFICATION_NOT_FOUND: "No pending email verification was found.", EMAIL_ALREADY_VERIFIED: "This email is already verified. You can log in.", OTP_ATTEMPTS_EXCEEDED: "Too many incorrect attempts. Request a new code.", OTP_DRIVER_NOT_AVAILABLE: "Email verification is temporarily unavailable. Please try again later." }; const response = NextResponse.json({ message: messages[authError.code ?? ""] ?? (authError.status >= 500 ? "Verification is temporarily unavailable. Please try again shortly." : authError.message), code: authError.code, errors: authError.errors }, { status: authError.status, headers: noStore }); if (authError.code === "EMAIL_VERIFICATION_NOT_FOUND" || authError.code === "EMAIL_ALREADY_VERIFIED") clearPendingVerification(response); return response; }
export async function POST(request: NextRequest) { let body: unknown; try { body = await request.json(); } catch { return NextResponse.json({ message: "Enter the six-digit verification code." }, { status: 400, headers: noStore }); } const otp = body && typeof body === "object" ? (body as Record<string, unknown>).otp : undefined; if (typeof otp !== "string" || !new RegExp(`^\\d{${otpLength}}$`).test(otp)) return NextResponse.json({ message: "Enter the six-digit verification code." }, { status: 422, headers: noStore }); const pending = await getPendingVerification(); if (!pending) return NextResponse.json({ message: "No pending email verification was found.", code: "PENDING_VERIFICATION_REQUIRED" }, { status: 400, headers: noStore }); try { const result = await authBackendRequest<LoginData>("auth/email/verify-otp", { method: "POST", body: { email: pending.email, otp }, language: request.headers.get("accept-language") ?? undefined }); if (!result.token || !isJobSeeker(result.user)) { if (result.token) { try { await authBackendRequest<null>("auth/logout", { method: "POST", token: result.token }); } catch {} } const response = NextResponse.json({ message: "This account is not available in the job-seeker experience.", code: "ROLE_NOT_SUPPORTED" }, { status: 403, headers: noStore }); clearPendingVerification(response); return response; } const response = NextResponse.json({ data: { user: result.user } }, { headers: noStore }); response.cookies.set(sessionCookieName, result.token, sessionCookieOptions); clearPendingVerification(response); return response; } catch (error) { return errorResponse(error); } }
