"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";
import { AuthClientError, register } from "@/lib/auth/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PasswordField } from "./password-field";

type RegisterFields = "name" | "email" | "phone" | "password" | "password_confirmation" | "terms_accepted";
type FieldErrors = Partial<Record<RegisterFields, string>>;
const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
function firstMessage(errors?: Record<string, string[]>) { return Object.fromEntries(Object.entries(errors ?? {}).map(([field, messages]) => [field, messages[0]])); }
function focusField(field: string) { requestAnimationFrame(() => document.getElementById(`register-${field}`)?.focus()); }

export function RegisterForm({ returnTo }: { returnTo?: string | null }) {
  const router = useRouter(); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [phone, setPhone] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [terms, setTerms] = useState(false); const [errors, setErrors] = useState<FieldErrors>({}); const [formError, setFormError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  function clear(field: RegisterFields) { setErrors((current) => ({ ...current, [field]: undefined })); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const nextErrors: FieldErrors = {}; if (!name.trim()) nextErrors.name = "Enter your full name."; if (!emailPattern.test(email.trim())) nextErrors.email = "Enter a valid email address."; if (!password) nextErrors.password = "Choose a password."; if (password !== confirmation) nextErrors.password_confirmation = "Passwords do not match."; if (!terms) nextErrors.terms_accepted = "You need to accept the terms to continue."; if (Object.keys(nextErrors).length) { setErrors(nextErrors); focusField(Object.keys(nextErrors)[0]); return; } setPending(true); setFormError(null); try { const result = await register({ name: name.trim(), email: email.trim(), ...(phone.trim() ? { phone: phone.trim() } : {}), password, password_confirmation: confirmation, terms_accepted: terms }, returnTo); setPassword(""); setConfirmation(""); router.replace(result.requires_email_verification ? "/verify-email" : "/login"); router.refresh(); } catch (reason) { const error = reason instanceof AuthClientError ? reason : new AuthClientError(503, "Registration is temporarily unavailable."); const mapped = firstMessage(error.errors) as FieldErrors; setErrors(mapped); setPassword(""); setConfirmation(""); setFormError(Object.keys(mapped).length ? null : error.message); if (Object.keys(mapped).length) focusField(Object.keys(mapped)[0]); } finally { setPending(false); } }
  const errorList = Object.entries(errors).filter(([, message]) => message);
  return <form className="auth-register-form mt-5 grid gap-4" noValidate onSubmit={submit}>{formError ? <div aria-live="assertive" className="radius-medium border border-border-danger bg-danger-surface p-4 type-body-small text-danger" role="alert">{formError}</div> : null}{errorList.length > 1 ? <div className="radius-medium border border-border-danger bg-danger-surface p-4 type-body-small text-danger" role="alert"><p className="font-semibold">Please correct the highlighted fields:</p><ul className="mt-2 list-disc ps-5">{errorList.map(([field, message]) => <li key={field}>{message}</li>)}</ul></div> : null}<div className="grid items-start gap-4 sm:grid-cols-2"><Input autoComplete="name" error={errors.name} id="register-name" label="Full name" onChange={(event) => { setName(event.target.value); clear("name"); }} required value={name} /><Input autoComplete="email" error={errors.email} id="register-email" label="Email address" onChange={(event) => { setEmail(event.target.value); clear("email"); }} required type="email" value={email} /></div><Input autoComplete="tel" error={errors.phone} id="register-phone" label="Phone number (optional)" onChange={(event) => { setPhone(event.target.value); clear("phone"); }} type="tel" value={phone} /><div className="grid items-start gap-4 sm:grid-cols-2"><PasswordField autoComplete="new-password" error={errors.password} id="register-password" label="Password" onChange={(value) => { setPassword(value); clear("password"); }} value={password} /><PasswordField autoComplete="new-password" error={errors.password_confirmation} id="register-password_confirmation" label="Confirm password" onChange={(value) => { setConfirmation(value); clear("password_confirmation"); }} value={confirmation} /></div><p className="-mt-1 type-body-small text-text-muted">Use a strong password you do not reuse elsewhere.</p><div className="grid gap-2"><label className="flex items-start gap-3 type-body-small text-text-secondary" htmlFor="register-terms_accepted"><input aria-describedby={errors.terms_accepted ? "register-terms-error" : undefined} aria-invalid={errors.terms_accepted ? true : undefined} checked={terms} className="auth-terms-checkbox shrink-0" id="register-terms_accepted" onChange={(event) => { setTerms(event.target.checked); clear("terms_accepted"); }} type="checkbox" /><span>I accept the <span className="font-semibold text-text-link">terms</span> required to create a Workey job-seeker account.</span></label>{errors.terms_accepted ? <p className="type-body-small text-danger" id="register-terms-error" role="alert">{errors.terms_accepted}</p> : null}</div><Button fullWidth loading={pending} type="submit">Create account</Button><p className="type-body-small text-text-secondary">Already have an account? <Link className="font-semibold" href="/login">Log in</Link>.</p></form>;
}
