"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState, type FormEvent } from "react";
import { AuthClientError, resendEmailOtp, verifyEmailOtp } from "@/lib/auth/client";
import { safeReturnTo } from "@/lib/auth/redirects";
import type { ResendVerificationMetadata } from "@/lib/auth/types";
import { maskEmail, otpLength, staticDemoOtp } from "@/lib/auth/verification";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { OtpInput } from "./otp-input";

interface VerifyEmailFormProps { initial?: { maskedEmail: string; deliveryChannel: string; expiresInSeconds: number; resendInSeconds: number; returnTo: string; }; }
function clock(seconds: number) { const safe = Math.max(0, seconds); return `${String(Math.floor(safe / 60)).padStart(2, "0")}:${String(safe % 60).padStart(2, "0")}`; }

export function VerifyEmailForm({ initial }: VerifyEmailFormProps) {
  const router = useRouter(); const [mode, setMode] = useState<"verify" | "recovery" | "already">(initial ? "verify" : "recovery"); const [maskedEmail, setMaskedEmail] = useState(initial?.maskedEmail ?? ""); const [deliveryChannel, setDeliveryChannel] = useState(initial?.deliveryChannel ?? ""); const [returnTo] = useState(initial?.returnTo ?? "/account"); const [expiresIn, setExpiresIn] = useState(initial?.expiresInSeconds ?? 0); const [resendIn, setResendIn] = useState(initial?.resendInSeconds ?? 0); const [otp, setOtp] = useState(""); const [email, setEmail] = useState(""); const [error, setError] = useState<string | null>(null); const [otpError, setOtpError] = useState<string | null>(null); const [verifyPending, setVerifyPending] = useState(false); const [resendPending, setResendPending] = useState(false); const [attemptsLocked, setAttemptsLocked] = useState(false);
  useEffect(() => { const timer = window.setInterval(() => { setExpiresIn((current) => Math.max(0, current - 1)); setResendIn((current) => Math.max(0, current - 1)); }, 1000); return () => window.clearInterval(timer); }, []);
  function applyMetadata(metadata: ResendVerificationMetadata, suppliedEmail?: string) { setDeliveryChannel(metadata.delivery_channel); setExpiresIn(metadata.expires_in_seconds); setResendIn(metadata.resend_after_seconds); if (suppliedEmail) setMaskedEmail(maskEmail(suppliedEmail)); setOtp(""); setOtpError(null); setAttemptsLocked(false); setMode("verify"); }
  async function resend() { setResendPending(true); setError(null); try { const result = await resendEmailOtp(mode === "recovery" ? email.trim() : undefined); applyMetadata(result.metadata, mode === "recovery" ? email.trim() : undefined); } catch (reason) { const authError = reason instanceof AuthClientError ? reason : new AuthClientError(503, "Email verification is temporarily unavailable."); if (authError.code === "OTP_RESEND_COOLDOWN" && authError.retryAfterSeconds) setResendIn(authError.retryAfterSeconds); setError(authError.message); } finally { setResendPending(false); } }
  async function verify(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (otp.length !== otpLength) { setOtpError("Enter all six digits of the verification code."); return; } setVerifyPending(true); setError(null); setOtpError(null); try { await verifyEmailOtp(otp); router.replace(safeReturnTo(returnTo)); router.refresh(); } catch (reason) { const authError = reason instanceof AuthClientError ? reason : new AuthClientError(503, "Verification is temporarily unavailable."); if (authError.code === "INVALID_OTP") { setOtp(""); setOtpError(authError.message); } else if (authError.code === "EMAIL_VERIFICATION_NOT_FOUND" || authError.code === "PENDING_VERIFICATION_REQUIRED") { setMode("recovery"); setOtp(""); setError("No pending verification was found. Request a new code to continue."); } else if (authError.code === "EMAIL_ALREADY_VERIFIED") { setMode("already"); setOtp(""); } else { if (authError.code === "OTP_ATTEMPTS_EXCEEDED") setAttemptsLocked(true); setError(authError.message); } } finally { setVerifyPending(false); } }
  if (mode === "already") return <div className="mt-5 ui-card ui-card--muted"><p className="type-heading-3 text-text-primary">Email already verified</p><p className="type-body mt-3 text-text-secondary">This email is already verified. You can log in to continue.</p><Link className="ui-button ui-button--primary mt-5" href="/login">Go to log in</Link></div>;
  if (mode === "recovery") return <div className="mt-5 grid gap-4"><p className="type-body text-text-secondary">Enter the email address you used to register. If it requires verification, Workey will prepare a code request.</p>{error ? <div className="radius-medium border border-border-danger bg-danger-surface p-4 type-body-small text-danger" role="alert">{error}</div> : null}<Input autoComplete="email" label="Email address" onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" type="email" value={email} /><Button disabled={!email.trim()} loading={resendPending} onClick={() => void resend()} type="button">Request verification code</Button><div className="flex flex-wrap gap-4 type-body-small"><Link href="/register">Create account</Link><Link href="/login">Return to log in</Link></div></div>;
  return <form className="mt-5 grid gap-4" onSubmit={verify}><p className="type-body text-text-secondary">Enter the six-digit code for <span className="font-semibold text-text-primary">{maskedEmail}</span>.</p>{deliveryChannel === "static" ? <p className="radius-medium border border-border-default bg-surface-muted p-3 type-body-small text-text-secondary">Project demo code: <span className="font-semibold text-text-primary">{staticDemoOtp}</span></p> : null}{error ? <div aria-live="assertive" className="radius-medium border border-border-danger bg-danger-surface p-4 type-body-small text-danger" role="alert">{error}</div> : null}<div className="grid gap-3"><p className="type-body-small text-text-secondary">Verification code</p><OtpInput disabled={verifyPending || attemptsLocked} error={otpError} onChange={setOtp} value={otp} />{otpError ? <p className="type-body-small text-danger" id="otp-error" role="alert">{otpError}</p> : null}</div><div className="flex flex-wrap items-center justify-between gap-3 type-body-small text-text-secondary"><span>{expiresIn ? `Code expires in ${clock(expiresIn)}` : "Code may have expired. Request a new one if needed."}</span><Button disabled={resendIn > 0 || resendPending} loading={resendPending} onClick={() => void resend()} size="small" type="button" variant="ghost">{resendIn > 0 ? `Resend in ${resendIn}s` : "Resend code"}</Button></div><Button disabled={attemptsLocked} fullWidth loading={verifyPending} type="submit">Verify email</Button><div className="flex flex-wrap gap-4 type-body-small"><Link href="/login">Change email or return to log in</Link><Link href="/">Return to Workey</Link></div></form>;
}
